name: SFDX Create Scratch Org

on: 
    workflow_dispatch:
      inputs:
        environment:
          description: 'Nome da Scratch'     
          required: true
          default: 'my-scratch'
    push:
      branches: 
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: 'Nome'  
        run: 'echo ${{ github.event.inputs.environment }}'            
      - name: Write the token into a file
        run: 'echo ${{ secrets.AUTH_SECRET}} > token.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
      - name: Create scratch org
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a  ${{ github.event.inputs.environment }} '
      - name: Push source
        run: 'sfdx force:source:push -u ${{ github.event.inputs.environment }}'
      - name: List orgs
        run: 'sfdx force:org:list'
      - name: Open org
        run : 'sfdx force:org:open -u ${{ github.event.inputs.environment }}'


