name: SFDX Create Scratch Org

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
        
      - name: 'Dev Hub'
        run: sfdx force:auth:web:login --setdefaultdevhubusername --setalias testehub
      - name: 'Create Scratch'
        run: sfdx force:org:create -f config/project-scratch-def.json -a teste -v testehub -s --durationdays 1
