name: SFDX Create Scratch Org

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
        
      - name: 'Create Scratch'
        run: sfdx force:org:create -f project-scratch-def.json -a teste --setdefaultusername --durationdays 1
